[sources.in]
type = "stdin"

[transforms.modify]
inputs = ["in"]
type="remap"
file = "modify.vrl"

[sinks.out]
inputs = ["modify"]
type = "file"
# this is the path to the new formatted log file
path = "logs/new.json"
encoding.codec = "text"
