[sources.in]
type = "file"
include = ["/Users/jatinsuri/VScode/otel-translation/vector_data/test.json"]
data_dir = "/Users/jatinsuri/VScode/otel-translation/vector_data"

[transforms.modify]
inputs = ["in"]
type="remap"
file = "/Users/jatinsuri/VScode/otel-translation/modify.vrl"

[sinks.out]
inputs = ["modify"]
type = "file"
path = "/Users/jatinsuri/VScode/otel-translation/vector_data/modified.json"
encoding.codec = "text"