# Vector config for tests that read from stdin and print filtered events to stdout

[sources.in]
type = "file"
include = ["/Users/jatinsuri/VScode/otel-translation/vector_data/viaq.json"]
data_dir = "/Users/jatinsuri/VScode/otel-translation/vector_data"

[transforms.modify]
inputs = ["in"]
type="remap"
file = "modify.vrl"

[sinks.out]
inputs = ["modify"]
type = "file"
path = "/Users/jatinsuri/VScode/otel-translation/vector_data/modified.json"
encoding.codec = "text"