# Vector config for tests that read from stdin and print filtered events to stdout
data_dir = "vector_data"

[sources.in]
type = "file"
include = [ "test.json" ]

[transforms.modify]
inputs = ["in"]
type="remap"
file = "modify.vrl"

[sinks.out]
inputs = ["modify"]
type = "console"
encoding.codec = "text"
